### ISSUE TITLE
ESP8266: JPG image from SPIFFS gets wrong decoding

### ISSUE THREAD

**Issue by nikola-winmaker** [Bodmer/JPEGDecoder#13] opened 2017-06-18 19:52 UTC
Hi all,
Great library! you made a great job!

I'm having some issue when running JPG decoding from SPIFFS,
The same sketch running from SD card runs perfectly. 
The same JPG image is on SD card and on spiffs.

What i'm seeing when calling jpegInfo() is that values are shifted down:
Width     0
Height    160
Components 128
and so on...

Picture is 160x128.

This is only happening when running sketch from SPIFFS.
The image is uploaded to SPIFFS via Arduino  ESP8266 Sketch Data Upload tool.
I uploaded JPG image for reference.

Best Regards,
Nikola

![cake29](https://user-images.githubusercontent.com/6199483/27263761-49507372-5470-11e7-9c09-3be53e2970cc.jpg)

**Comment by Bodmer** [comment] 2017-06-21 13:47
This is not something I have encountered.  I suspect this is a bug in the SPIFFS code that is part of the ESP8266 board package core.  [See here](https://github.com/esp8266/Arduino/pull/3261). In which case this should be fixed when version 2.4.0 of the Arduino core is released.

**Comment by Bodmer** [comment] 2017-06-23 00:11
OK, update: I have witnessed a similar problem where the values returned by jpegInfo() are wrong. This appears to be due to a corrupted pointer that affects the values read out of a struct that contains the values.  One of the values (Components) is a hard coded value of 1 and this seems to end up being reported as a different value.

I think this might be a bug in the ESP8266 core but have not been able to isolate the root cause.

**Closed** 2018-01-23 19:32 UTC
